//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Dtos.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TMS.Dtos.Resources.ValidationResources", typeof(ValidationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email address.
        /// </summary>
        public static string Invalid_email_address {
            get {
                return ResourceManager.GetString("Invalid_email_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum 16 characters allowed.
        /// </summary>
        public static string Maximum_16_characters_allowed {
            get {
                return ResourceManager.GetString("Maximum_16_characters_allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum {0} characters allowed.
        /// </summary>
        public static string Maximum_characters_allowed {
            get {
                return ResourceManager.GetString("Maximum_characters_allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum 8 characters required.
        /// </summary>
        public static string Minimum_8_characters_required {
            get {
                return ResourceManager.GetString("Minimum_8_characters_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum {0} characters required.
        /// </summary>
        public static string Minimum_characters_required {
            get {
                return ResourceManager.GetString("Minimum_characters_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and confirm password missmatched.
        /// </summary>
        public static string Password_and_confirm_password_missmatched {
            get {
                return ResourceManager.GetString("Password_and_confirm_password_missmatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must have at least 1 lower case, 1 upper case,  1 number and 1 special character.
        /// </summary>
        public static string Password_must_have_atleast {
            get {
                return ResourceManager.GetString("Password_must_have_atleast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number must be formated as 03xxxxxxxxx.
        /// </summary>
        public static string Phone_number_must_be_formated_as {
            get {
                return ResourceManager.GetString("Phone_number_must_be_formated_as", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide confirmation of password.
        /// </summary>
        public static string Provide_confirmation_of_password {
            get {
                return ResourceManager.GetString("Provide_confirmation_of_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide email address.
        /// </summary>
        public static string Provide_email_address {
            get {
                return ResourceManager.GetString("Provide_email_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide first name.
        /// </summary>
        public static string Provide_first_name {
            get {
                return ResourceManager.GetString("Provide_first_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide last name.
        /// </summary>
        public static string Provide_last_name {
            get {
                return ResourceManager.GetString("Provide_last_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide password for login.
        /// </summary>
        public static string Provide_password_for_login {
            get {
                return ResourceManager.GetString("Provide_password_for_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide username.
        /// </summary>
        public static string Provide_username {
            get {
                return ResourceManager.GetString("Provide_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select staff role.
        /// </summary>
        public static string Select_staff_role {
            get {
                return ResourceManager.GetString("Select_staff_role", resourceCulture);
            }
        }
    }
}
